

class player{
  int id;
  String name;
  String img;
int Goals;
int award;
String t1;
String te1;
String t2;
  String te2;
String t3;
  String te3;


  player(this.id, this.name, this.img, this.Goals, this.award, this.t1,
      this.te1, this.t2, this.te2, this.t3, this.te3,);
}
List<player>plyr=[
 player(1,'Lionel Messi', 'images/messi.png',827,87,"Overview","Lionel Messi is an Argentine professional footballer who plays as a forward and captains both Ligue 1 club Paris Saint-Germain and the Argentina national team. He is widely considered to be one of the greatest players of all time and has won a record seven Ballon d'Or awards.\nMessi was born in Rosario, Argentina, on June 24, 1987. He suffers from growth hormone deficiency, which caused him to have growth problems at a young age. In 2000, FC Barcelona recognized Messi's potential and agreed to pay for his treatment in exchange for him signing a contract with the club.","The Beginning","Messi began his professional career with Barcelona in 2003 and quickly became one of the best players in the world. He won numerous trophies with Barcelona, including ten La Liga titles, four UEFA Champions League titles, and three FIFA Club World Cups.\nMessi scored 672 goals in 778 appearances for Barcelona, making him the club's all-time leading scorer. He is also the all-time leading scorer in La Liga with 474 goals.\nIn 2021, Messi moved to Paris Saint-Germain. He won the Ligue 1 title in his first season with the club, scoring 34 goals in 45 appearances.\nOn the international stage, Messi led Argentina to victory in the 2021 Copa América. This was Argentina's first major international title since 1986.","Achievements","Ballon d'Or: 7 times (2009, 2010, 2011, 2012, 2015, 2019, 2021)\nFIFA The Best: 2 times (2019, 2022)\nEuropean Golden Shoe: 6 times (2009–10, 2011–12, 2012–13, 2016–17, 2017–18, 2018–19)\nUEFA Best Player in Europe: 2 times (2011, 2015)\nIFFHS World Player of the Year: 6 times (2009, 2011, 2012, 2015, 2019, 2021)\nAFC Asian Player of the Year: 3 times (2009, 2011, 2012)\nSouth American Footballer of the Year: 10 times (2007, 2008, 2009, 2010, 2011, 2012, 2015, 2019, 2021, 2022)\nLa Liga Best Player: 8 times (2009, 2010, 2011, 2012, 2013, 2015, 2018, 2019)\nLa Liga Best Forward: 7 times (2009, 2010, 2011, 2012, 2013, 2015, 2016)\nPichichi Trophy: 8 times (2010, 2012, 2013, 2017, 2018, 2019, 2020, 2021)\nFIFA World Cup Best Player: 2 times (2014, 2022)\nCopa América Best Player: 1 time (2021)\n\nMessi is 1.70 meters tall and weighs 67 kilograms.\nLionel Messi is married to Antonella Roccuzzo. They married on June 30, 2017, and have three children together: Thiago (born on November 2, 2012), Mateo (born on September 11, 2015), and Ciro (born on March 10, 2018)."),
  player(2,'Cristiano Ronaldo', 'images/CR.jpg',876,67,'Overview',"Cristiano Ronaldo dos Santos Aveiro, a Portuguese professional footballer who plays as a right-winger or striker for Premier League club Manchester United and captains the Portugal national team. He is widely regarded as one of the greatest players of all time, and has won numerous individual and team awards throughout his career.","The Beginning","Ronaldo began his professional career with Sporting CP in 2002, before moving to English club Manchester United in 2003 for £12 million. At Manchester United, Ronaldo won five Premier League titles, three UEFA Champions League titles, the FIFA Club World Cup, the FA Cup, and three League Cup titles. He also won the Ballon d'Or four times and the FIFA World Player of the Year once.In 2018, Ronaldo moved to Spanish club Real Madrid for €100 million, the highest fee ever paid for a football player at the time. At Real Madrid, Ronaldo won three La Liga titles, two UEFA Champions League titles, the FIFA Club World Cup, two UEFA Super Cup titles, and one Copa del Rey. He also won the Ballon d'Or again in 2017.In 2021, Ronaldo moved to Italian club Juventus for €100 million, the highest fee ever paid for a player in Italian football. At Juventus, Ronaldo won two Serie A titles, one Coppa Italia title, and one Supercoppa Italiana title.","Achievements","Ballon d'Or: 5 times (2008, 2013, 2014, 2016, 2017)\nFIFA World Player of the Year: 1 time (2008)\nUEFA Men's Player of the Year: 4 times (2008, 2013, 2014, 2016)\nPremier League Player of the Year: 3 times (2007, 2008, 2009)\nLa Liga Player of the Year: 2 times (2013, 2014)\nSerie A Player of the Year: 1 time (2020)\nLa Liga top scorer: 4 times (2011, 2012, 2013, 2014)\nPremier League top scorer: 3 times (2007, 2008, 2009)\nSerie A top scorer: 1 time (2020)\nUEFA Champions League top scorer: 7 times (2008, 2013, 2014, 2015, 2016, 2017, 2018)\nFIFA Club World Cup top scorer: 7 times (2008, 2013, 2014, 2016, 2017, 2018, 2019)\nUEFA European Championship winner: 2016UEFA Nations League winner: 2019\nUEFA European Championship top scorer: 2016\nUEFA Nations League top scorer: 2019,\nCristiano Ronaldo is 1.87 meters tall and weighs 84 kilograms.\nRonaldo is married to Georgina Rodríguez, and has five children."),
   player(4,'Erling Haaland', 'images/Erling Haaland.jpg',233,20,"Overview","Erling Haaland is a professional Norwegian footballer who plays as a striker for Premier League club Manchester City and captains the Norway national team. He is considered one of the best strikers in the world and has won numerous individual and team awards throughout his career.","The Beginning","Haaland began his professional career with Norwegian club Molde in 2017, where he won the Norwegian League and Norwegian Cup in 2019. In 2019, Haaland moved to German club Borussia Dortmund for €20 million, the most expensive transfer fee for a Norwegian player at the time.\nWith Borussia Dortmund, Haaland won the German Cup in 2021. Haaland also won the German Bundesliga Golden Boot in the 2019-20 and 2020-21 seasons.\nIn 2022, Haaland moved to Manchester City for €60 million, the most expensive transfer fee for a Norwegian player in the history of football.","Achievements","German Bundesliga Golden Boot (2019-20, 2020-21)\nBundesliga Player of the Year (2020-21)\nUEFA Champions League top scorer (2020-21)\nGolden Boy Award (2020)\n\nErling Haaland is 1.94 meters tall and weighs 95 kilograms.\nHaaland is married to Raija Blomqvist and has one son."),
  player(3,'Karim Benzema', 'images/Karim Benzema.jpg',470,37,"Overview","Karim Benzema is a French professional footballer who plays as a striker for La Liga club Real Madrid and captains the France national team. He is considered one of the best strikers in the world and has won numerous individual and team awards throughout his career.","The Beginning","Benzema began his professional career with French club Lyon in 2004, where he won the Ligue 1 title and Coupe de France in 2008. In 2009, Benzema moved to Real Madrid for €94 million, the most expensive transfer fee for a French player at the time.\nWith Real Madrid, Benzema has won the La Liga title 5 times, Copa del Rey 4 times, Supercopa de España 4 times, and the UEFA Champions League 5 times. He has also won the La Liga Player of the Season award (2022) and the Ballon d'Or award (2022).","Achievements","Ballon d'Or (2022)\nLa Liga Player of the Season (2022),\nLa Liga top scorer (2022)\nUEFA Champions League top scorer (2022)\nFrance national team top scorer\nFIFA World Cup winner (2018)\nUEFA European Championship winner (2021)\n\nKarim Benzema is 1.85 meters tall and weighs 79 kilograms.\nBenzema married Cora Gauthier in 2016 and has four children."),
  player(9,'Kevin de Bruyne', 'images/Kevin de Bruyne.jpg',254,25,"Overview","is a Belgian professional footballer who plays as an attacking midfielder for Premier League club Manchester City and captains the Belgium national team. He is widely regarded as one of the best midfielders in the world, and has won numerous individual and team awards throughout his career.","The Beginning","De Bruyne began his professional career with Belgian club Genk in 2008, where he won the Belgian Pro League and Belgian Cup in 2011. In 2012, De Bruyne moved to English club Chelsea, but he did not play many minutes in his first season. In 2013, De Bruyne moved to German club Wolfsburg, where he began to show his true talent. In his first season with Wolfsburg, he won the DFB-Pokal and reached the UEFA Champions League final. In 2015, De Bruyne won the Bundesliga Player of the Season award.\nIn 2015, De Bruyne moved to Manchester City for €55 million, the most expensive transfer fee for a Belgian player at the time. With Manchester City, De Bruyne has won the Premier League title four times, the FA Cup four times, the EFL Cup six times, and the UEFA Champions League once. De Bruyne has also won the Premier League Player of the Season award (2019-20) and the UEFA Men's Player of the Year award (2019-20).","Achievements","Premier League Player of the Season (2019-20)\nUEFA Men's Player of the Year (2019-20)\nBundesliga Player of the Season (2015)\n Bundesliga top scorer (2015)\nBundesliga Player of the Year (2015),\n Belgian Golden Shoe (2011, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021)\nUEFA European Championship winner (2021)\n FIFA World Cup runner-up (2018)\n\nDe Bruyne is 1.81 m (5 ft 11 in) tall and weighs 75 kg (165 lb).\nDe Bruyne is married to Michele Lacroix and has two children."),
  player(5,'Kulian Mbappe', 'images/Kulian Mbappe.jpg',274,35,"Overview","Kylian Mbappé, a French professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and captains the France national team. He is considered one of the best young players in the world, and has won numerous individual and team awards throughout his career.","The Beginning","Mbappé began his professional career with Monaco in 2015, where he won the Ligue 1 title and Coupe de France in 2016. In 2017, he moved to Paris Saint-Germain for €180 million, the most expensive transfer deal for a football player at the time.\nWith Paris Saint-Germain, Mbappé has won four Ligue 1 titles, three Coupe de France titles, three Coupe de la Ligue titles, and the UEFA Champions League in 2022. He has also won the UEFA European Under-19 Championship Golden Player award in 2016, and the FIFA World Young Player of the Year award in 2018.","Achievements","UEFA European Under-19 Championship Golden Player (2016)\nFIFA World Young Player of the Year (2018)\nFrench Golden Ball (2018)\nLigue 1 Player of the Year (2019)\nLigue 1 top scorer (2019)\nUEFA Champions League top scorer (2022)\nFIFA U-20 World Cup winner (2018)\nUEFA European Championship winner (2021)\nKylian Mbappé is 1.78 meters tall and weighs 78 kilograms.\nMbappé was born in Paris, France, to a father from Guinea and a mother from Morocco. He has one sister."),
  player(6,'Matthijs de Ligt', 'images/Matthijs de Ligt.jpg',14,13,"Overview","Matthijs de Ligt is a Dutch professional footballer who plays as a centre-back for Serie A club Juventus and captains the Netherlands national team. He is considered one of the best defenders in the world and has won numerous individual and team awards throughout his career.","The Beginning","De Ligt began his professional career with Dutch club Ajax Amsterdam in 2016, where he won the Eredivisie title and KNVB Cup in 2019. In 2019, De Ligt moved to Italian club Juventus for €75 million, the most expensive transfer fee for a Dutch player at the time.\nWith Juventus, De Ligt has won the Serie A title once, the Coppa Italia once, and the Supercoppa Italiana once. De Ligt has also won the Serie A Young Player of the Season award (2019-20).","Achievements","Serie A Young Player of the Season (2019-20)\nGolden Boy award (2018)\n UEFA Team of the Year (2019)\nUEFA Team of the Year (2020)\nUEFA Team of the Year (2021)\nUEFA European Championship winner (2021)\n\nMatthijs de Ligt is 1.90 m (6 ft 3 in) tall and weighs 80 kg (176 lb).\nDe Ligt is married to Anna Rose Bonari and has a child"),
  player(7,'Mohamad Salah', 'images/Mohamad Salah.jpg',330,26,"Overview","Mohamed Salah is a professional Egyptian footballer who plays as a right-winger for Premier League club Liverpool and captains the Egypt national team. He is considered one of the best players in the world and has won numerous individual and team awards throughout his career.","The beginning","Salah began his professional career with El Mokawloon Sporting Club in 2010 before moving to Swiss club Basel in 2012. At Basel, Salah won the Swiss Super League and Swiss Cup in 2013. In 2014, Salah moved to English club Chelsea, but he did not play many minutes in his first season. In 2015, Salah moved to Italian club Roma, where he began to show his true talent. In his first season with Roma, Salah won the Serie A Golden Boot and was awarded the Serie A MVP.\nIn 2017, Salah moved to Liverpool for €42 million, the most expensive transfer fee for an Egyptian player at the time. With Liverpool, Salah has won the Premier League title in 2020 and the UEFA Champions League in 2019. Salah also won the Premier League Golden Boot in the 2017-18 and 2022-23 seasons, and the Premier League Player of the Season award in the 2022-23 season.","Achievements","Premier League Golden Boot (2017-18, 2022-23)\nPremier League Player of the Season (2022-23)\nAfrican Footballer of the Year (2017, 2018, 2021, 2022)\nBBC African Footballer of the Year (2018, 2019, 2022)\nCAF African Footballer of the Year (2017, 2018, 2021, 2022\nAfrica Cup of Nations winner (2021)\nAfrica Cup of Nations top scorer (2021)\n\nMohamed Salah is 1.75 meters tall and weighs 73 kilograms.\nSalah is married to Magi Sadiq and has one daughter."),
  player(8,'Robert Lewandowski', 'images/Robert Lewandowski.jpg',565,57,"Overview","Robert Lewandowski is a Polish professional footballer who plays as a striker for Bundesliga club Bayern Munich and captains the Poland national team. He is considered one of the best strikers in the world and has won numerous individual and team awards throughout his career.","The Beginning","Lewandowski began his professional career with Polish club Lech Poznań in 2008, where he won the Ekstraklasa title and Polish Cup in 2010. In 2010, Lewandowski moved to German club Borussia Dortmund, where he won the Bundesliga title once, the DFB-Pokal twice, the DFL-Supercup twice, and the UEFA Europa League once.\nIn 2014, Lewandowski moved to Bayern Munich for €45 million, the most expensive transfer fee for a Polish player at the time. With Bayern Munich, Lewandowski has won the Bundesliga title 10 times, the DFB-Pokal 6 times, the DFL-Supercup 6 times, and the UEFA Champions League once. Lewandowski has also won the Bundesliga Player of the Season award seven times and the UEFA Men's Player of the Year award twice"," Achievements","Bundesliga Player of the Season (2013-2014, 2014-2015, 2015-2016, 2016-2017, 2017-2018, 2018-2019, 2019-2020, 2020-2021)\nUEFA Men's Player of the Year (2020, 2021)\n Bundesliga top scorer (2013-2014, 2014-2015, 2015-2016, 2016-2017, 2017-2018, 2018-2019, 2019-2020, 2020-2021, 2021-2022)\nUEFA Champions League top scorer (2019-2020, 2021-2022)\nPoland national team top scorer\nPoland national team top scorer\n\nRobert Lewandowski is 1.85 m (6 ft 1 in) tall and weighs 80 kg (176 lb).\nLewandowski is married to Anna Stachurska and has two daughters."),
  player(10,'Sadio Mane', 'images/Sadio Mane.jpg',276,22,"Overview","Sadio Mane is a Senegalese professional footballer who plays as a forward for Bundesliga club Bayern Munich and the Senegal national team. He is considered one of the best players in the world, and has won numerous individual and team awards throughout his career.","The Beginning","Mane began his professional career with French club Metz in 2011, where he won the Coupe de France in 2013. In 2014, Mane moved to Austrian club Salzburg, where he won the Austrian Bundesliga and Austrian Cup in 2015.\nIn 2016, Mane moved to English club Liverpool, where he won the Premier League title twice, the FA Cup once, the League Cup once, and the UEFA Champions League once. Mane has also won the African Footballer of the Year award three times (2019, 2020, 2022).","Achievements"," African Footballer of the Year (2019, 2020, 2022)\n UEFA Team of the Year (2019, 2022)\nFIFA World XI (2019, 2022)\nPremier League Golden Boot (2018-2019)\n Premier League Player of the Season (2018-2019)\nAfrica Cup of Nations winner (2022)\n\nSadio Mane is 1.75 m (5 ft 9 in) tall and weighs 70 kg (154 lb).\nMane is married to Saly Mane, and they have three children."),
];
class quotes{
  int id;
  String name;
  String img;
  String quote;

  quotes(this.id, this.name, this.img, this.quote);
}
List<quotes>Quotes=[
  quotes(2,'Cristiano Ronaldo', 'images/CR.jpg','Talent without hard work is nothing.'),
  quotes(2,'Cristiano Ronaldo', 'images/CR.jpg','Your love makes me stronger, but your hate makes me unstoppable.'),
  quotes(2,'Cristiano Ronaldo', 'images/CR.jpg','I dont have to show anything to anyone or prove anything to anyone.'),
  quotes(4,'Erling Haaland', 'images/Erling Haaland.jpg','Nothing is impossible.'),
  quotes(4,'Erling Haaland', 'images/Erling Haaland.jpg','I want to be the best in the world.'),
  quotes(4,'Erling Haaland', 'images/Erling Haaland.jpg','I love football more than anything else in the world.'),
  quotes(3,'Karim Benzema', 'images/Karim Benzema.jpg','Im not a pure striker, Im a No. 9 with a No. 10 mentality.'),
  quotes(3,'Karim Benzema', 'images/Karim Benzema.jpg','I learn every day, and I want to be the best player in the world.'),
  quotes(3,'Karim Benzema', 'images/Karim Benzema.jpg','I learn every day, and I want to be the best player in the world.'),
  quotes(9,'Kevin de Bruyne', 'images/Kevin de Bruyne.jpg','I always try to be the best version of myself, both on and off the pitch.'),
  quotes(9,'Kevin de Bruyne', 'images/Kevin de Bruyne.jpg','I think football is about making the right decisions at the right moment.'),
  quotes(9,'Kevin de Bruyne', 'images/Kevin de Bruyne.jpg','Even if you are a professional, you need to have fun when you are on the field. If you dont enjoy your job, you dont have fun. There will be ups and downs.'),
  quotes(5,'Kulian Mbappe', 'images/Kulian Mbappe.jpg','I want to be the best in the world.'),
  quotes(5,'Kulian Mbappe', 'images/Kulian Mbappe.jpg','Dreaming is not enough. You have to work hard to achieve it.'),
  quotes(5,'Kulian Mbappe', 'images/Kulian Mbappe.jpg','Dont compare yourself to anyone. Just be the best version of yourself.'),
  quotes(6,'Matthijs de Ligt', 'images/Matthijs de Ligt.jpg','Winning is the most important thing to me. I dont care about winning the Ballon dOr or anyother awards if I dont win trophies.'),
  quotes(6,'Matthijs de Ligt', 'images/Matthijs de Ligt.jpg','I learn and improve every day. I want to be the best defender in the world, and I believe I acapable of achieving that.'),
  quotes(6,'Matthijs de Ligt', 'images/Matthijs de Ligt.jpg','I want to be an inspiration to others, especially young players. I want to show them that theycan achieve anything if they work hard.'),
  quotes(7,'Mohamad Salah', 'images/Mohamad Salah.jpg','I love football, and its everything to me. I want to play at the highest level possible and wintrophies.'),
  quotes(7,'Mohamad Salah', 'images/Mohamad Salah.jpg','I want to win the World Cup with Egypt.'),
  quotes(7,'Mohamad Salah', 'images/Mohamad Salah.jpg','I want to be the best player in the world'),
  quotes(8,'Robert Lewandowski', 'images/Robert Lewandowski.jpg','Winning is the most important thing to me. I dont care about individual numbers if I dont win trophies.'),
  quotes(8,'Robert Lewandowski', 'images/Robert Lewandowski.jpg','I want to be the best player in the world. I know that will require a lot of hard work andcommitment, but I am ready for it.'),
  quotes(8,'Robert Lewandowski', 'images/Robert Lewandowski.jpg','I love football, and its everything to me. I want to play at the highest level possible and wintrophies with my team and my country.'),
  quotes(1,'Lionel Messi', 'images/messi.png','Hard work and perseverance are the keys to success.'),
  quotes(1,'Lionel Messi', 'images/messi.png','If you believe in yourself, you can achieve anything.'),
  quotes(1,'Lionel Messi', 'images/messi.png','I want to be the best in the world.'),
  quotes(10,'Sadio Mane', 'images/Sadio Mane.jpg','Dont be afraid to dream big, nothing is impossible if you put your mind to it.'),
  quotes(10,'Sadio Mane', 'images/Sadio Mane.jpg','I never want to settle for mediocrity, I always strive for greatness'),
  quotes(10,'Sadio Mane', 'images/Sadio Mane.jpg','The most important thing is the team. I always want to help the team win, and if I can scoregoals, that s great.'),
];